const STORAGE_KEY = 'samenThuisV2';
const PAGES = ['today','agenda','tasks','challenges','programs','mealplan','groceries','deals','weather','stock','home','budget','dates','travel','extras','settings'];
const pageTitles = {today:'Vandaag',agenda:'Agenda',tasks:'Taken',challenges:'Challenges',programs:'Programma’s',mealplan:'Weekmenu',groceries:'Boodschappen',deals:'Acties & aanbiedingen',weather:'Weer',stock:'Voorraad',home:'Woning',budget:'Budget',dates:'Date Ideeën',travel:'Reizen',extras:'Extra',settings:'Instellingen'};
const PEOPLE = ['Kees','Daphne','Samen'];
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const todayKey = () => new Date().toISOString().slice(0,10);
const dailyQuotes = [
  'Je hoeft niet alles vandaag te doen. Begin met één kleine stap.',
  'Een fijn thuis ontstaat door kleine dingen die je samen blijft doen.',
  'Vooruitgang is niet altijd groot; soms is het gewoon blijven proberen.',
  'Maak ruimte voor wat belangrijk is, niet alleen voor wat dringend is.',
  'Aandacht is een kleine moeite met een groot effect.',
  'Samen hoeft niet perfect te zijn. Samen is al waardevol.',
  'Rust is ook iets wat je bewust kunt plannen.',
  'Een gewoon moment kan bijzonder worden als je er aandacht aan geeft.',
  'Kleine gewoontes maken het leven lichter.',
  'Je hoeft niet dezelfde dag te hebben om elkaar toch te begrijpen.'
];
const dailyQuestions = [
  'Wat zou vandaag voor jou een fijne dag maken?',
  'Waar ben je deze week trots op, groot of klein?',
  'Wat kunnen we vandaag doen om elkaar wat makkelijker te helpen?',
  'Welk klein moment samen wil je deze week graag creëren?',
  'Wat geeft jou op dit moment de meeste rust?',
  'Welke gewoonte zouden we samen graag wat vaker willen doen?',
  'Wat waardeer je op dit moment aan de ander?',
  'Wat wil je deze week graag afronden zodat er meer ruimte ontstaat?',
  'Welke plek of activiteit geeft jou direct een goed gevoel?',
  'Wat is iets kleins waar we ons vandaag op kunnen verheugen?',
  'Wat zou je graag eens samen willen leren of proberen?',
  'Wanneer voelde je je de afgelopen tijd echt gesteund?'
];
function dailyIndex(list){const d=new Date();const start=new Date(d.getFullYear(),0,0);const day=Math.floor((d-start)/86400000);return day%list.length}

function defaultState(){
  return {version:2,currentPage:'today',theme:'light',appearance:'normal',minimalColor:'#315f86',focus:'',tasks:[
    {id:uid(),text:'Wasmachine aanzetten',person:'Kees',category:'Huishouden',due:todayKey(),done:false,createdAt:Date.now()},
    {id:uid(),text:'Boodschappenlijst controleren',person:'Samen',category:'Boodschappen',due:todayKey(),done:false,createdAt:Date.now()}
  ],agenda:[],challenges:[
    {id:uid(),title:'3× bewegen deze week',category:'Sport',target:3,progress:1,points:50,done:false},
    {id:uid(),title:'30 minuten lezen',category:'Lezen',target:1,progress:0,points:20,done:false},
    {id:uid(),title:'Samen iets leuks doen',category:'Samen',target:1,progress:0,points:30,done:false}
  ],programs:[],deals:[],meals:[],groceries:[],stock:[],home:[],budget:{monthly:0,spent:0,items:[]},dates:[],travel:[],extras:[],dailyAnswers:{},notifications:true,history:[]};
}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?merge(defaultState(),JSON.parse(raw)):defaultState()}catch{return defaultState()}}
function merge(base,saved){return {...base,...saved,tasks:Array.isArray(saved.tasks)?saved.tasks:base.tasks,challenges:Array.isArray(saved.challenges)?saved.challenges:base.challenges,programs:Array.isArray(saved.programs)?saved.programs:base.programs,deals:Array.isArray(saved.deals)?saved.deals:base.deals}}
let state=loadState();
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function saveState(message='Opgeslagen'){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); if(message) toast(message); return true}catch{toast('Opslag niet beschikbaar');return false}}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(message){const r=$('#toast-region');if(!r)return;const t=document.createElement('div');t.className='toast';t.textContent=message;r.append(t);setTimeout(()=>t.remove(),2400)}
function showPage(page){if(!PAGES.includes(page))page='today';PAGES.forEach(p=>$(`#page-${p}`)?.classList.toggle('is-active',p===page));$$('[data-page-link]').forEach(x=>x.classList.toggle('is-active',x.dataset.pageLink===page));state.currentPage=page;$('#pageTitle').textContent=pageTitles[page];closeMenu();renderPage(page);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function renderPage(page){({today:renderToday,tasks:renderTasksPage,challenges:renderChallenges,programs:renderPrograms,agenda:renderAgenda,mealplan:renderMeals,groceries:renderGroceries,deals:renderDeals,weather:renderWeather,stock:renderStock,home:renderHome,budget:renderBudget,dates:renderDates,travel:renderTravel,extras:renderExtras,settings:renderSettings}[page]||renderToday)()}
function personAvatar(person){return person==='Daphne'?'D':person==='Samen'?'S':'K'}
function taskMarkup(task,index){return `<li class="task-row ${task.done?'is-done':''}" draggable="true" data-id="${task.id}" data-index="${index}"><span class="drag">⠿</span><input class="task-check" type="checkbox" ${task.done?'checked':''} aria-label="${esc(task.text)}"><span class="avatar avatar-${task.person==='Daphne'?'purple':task.person==='Samen'?'green':'blue'}">${personAvatar(task.person)}</span><span class="task-label"><strong>${esc(task.text)}</strong><small>${esc(task.category)} · ${esc(task.person)}${task.due?` · ${esc(task.due)}`:''}</small></span><button class="icon-button task-delete" aria-label="Taak verwijderen">×</button></li>`}
function renderToday(){
  const today=todayKey();
  $('#today-date-label').textContent=new Date().toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'});
  $('#daily-quote').textContent='“'+dailyQuotes[dailyIndex(dailyQuotes)]+'”';
  $('#daily-question').textContent=dailyQuestions[dailyIndex(dailyQuestions)];
  if($('#daily-answer'))$('#daily-answer').value=(state.dailyAnswers||{})[today]||'';
  if($('#daily-answer-status'))$('#daily-answer-status').textContent=(state.dailyAnswers||{})[today]?'Antwoord van vandaag is bewaard.':'Je antwoord blijft lokaal bewaard.';
  $('#focus-current').textContent=state.focus||'Nog geen focus gekozen.';$('#focus-current').classList.toggle('empty-state',!state.focus);
  const open=state.tasks.filter(t=>!t.done);$('#task-list').innerHTML=open.slice(0,5).map(taskMarkup).join('')||'<li class="empty-row">Geen openstaande taken 🎉</li>';$('#task-count').textContent=`${open.length} openstaande taak${open.length===1?'':'taken'}`;
  $('#today-stats').innerHTML=`<article class="stat-tile"><span>Open taken</span><strong>${open.length}</strong><small>${state.tasks.length?`${state.tasks.filter(t=>t.done).length} afgerond`: 'Nog niets afgerond'}</small></article><article class="stat-tile"><span>Challenges</span><strong>${state.challenges.filter(c=>c.done).length}/${state.challenges.length}</strong><small>${state.challenges.reduce((a,c)=>a+(Number(c.progress||0)*Number(c.points||0)/Math.max(1,Number(c.target||1))),0).toFixed(0)} punten in opbouw</small></article>`;
  const challenge=state.challenges.find(c=>!c.done)||state.challenges[0];$('#today-challenge').innerHTML=challenge?`<div class="dashboard-challenge"><span class="tag">${esc(challenge.category||'Challenge')}</span><h3>${esc(challenge.title)}</h3><div class="progress"><span style="width:${Math.min(100,Number(challenge.progress||0)/Math.max(1,Number(challenge.target||1))*100)}%"></span></div><div class="row-between"><small>${Number(challenge.progress||0)}/${Number(challenge.target||1)} keer · ${Number(challenge.points||0)} punten</small><button class="button button-primary button-small challenge-progress" data-id="${challenge.id}">${challenge.progress>=challenge.target?'Voltooid ✓':'Check-in'}</button></div></div>`:'<div class="empty-row">Nog geen challenges. Voeg er een toe op de Challenges-pagina.</div>';
  const agenda=state.agenda.filter(a=>!a.date||a.date>=today).sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(0,3);$('#today-agenda').innerHTML=agenda.length?agenda.map(a=>`<div class="list-card"><div><strong>${esc(a.title)}</strong><small>${a.date?new Date(a.date+'T12:00').toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'}):'Datum niet ingesteld'} · ${esc(a.person||'Samen')}</small></div></div>`).join(''):'<div class="empty-row">Geen komende afspraken ingevoerd.</div>';
  $('#dashboard-grocery-count').textContent=`${state.groceries.filter(g=>!g.done).length} producten op de lijst`;
  const deals=state.deals.filter(d=>(!d.valid||d.valid>=today)&&state.groceries.some(g=>!g.done&&(g.name.toLowerCase().includes(d.product.toLowerCase())||d.product.toLowerCase().includes(g.name.toLowerCase()))));$('#today-deals').innerHTML=deals.length?deals.map(d=>`<div class="list-card"><div><strong>${esc(d.product)} · € ${Number(d.price).toFixed(2)}</strong><small>${esc(d.store)} · geldig t/m ${esc(d.valid||'onbekend')}</small></div><button class="button button-secondary button-small" data-page-link="deals">Bekijken</button></div>`).join(''):'<div class="empty-row">Nog geen matches met jullie boodschappenlijst.</div>';
  const meals=state.meals.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);$('#meal-preview').innerHTML=meals.length?meals.map(x=>`<div class="meal-item"><span class="meal-day">${new Date(x.date+'T12:00').toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'})}</span><span class="meal-name">${esc(x.name)}</span></div>`).join(''):'<div class="empty-row">Nog geen maaltijden gepland.</div>';
}
function addTask(text,person='Samen',category='Huishouden',due=todayKey()){if(!text.trim())return;state.tasks.unshift({id:uid(),text:text.trim(),person,category,due,done:false,createdAt:Date.now()});renderPage(state.currentPage);saveState()}
function renderTasksPage(){const list=$('#all-task-list');if(!list)return;list.innerHTML=state.tasks.map(taskMarkup).join('')||'<li class="empty-row">Nog geen taken.</li>';$('#task-open-count').textContent=state.tasks.filter(t=>!t.done).length}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;if(t.done)state.history.unshift({type:'task',text:t.text,at:new Date().toISOString()});renderToday();renderTasksPage();saveState(t.done?'Taak afgerond ✓':'Taak opnieuw geopend')}
function deleteTask(id){state.tasks=state.tasks.filter(x=>x.id!==id);renderToday();renderTasksPage();saveState('Taak verwijderd')}
function renderAgenda(){const el=$('#agenda-list');const items=[...state.agenda].sort((a,b)=>a.date.localeCompare(b.date));el.innerHTML=items.map((x,i)=>`<li class="list-card"><div><strong>${esc(x.title)}</strong><small>${esc(x.date)} · ${esc(x.person)}</small></div><button class="icon-button delete-generic" data-type="agenda" data-id="${x.id}">×</button></li>`).join('')||'<li class="empty-row">Nog geen afspraken.</li>'}
function renderChallenges(){const el=$('#challenge-list');el.innerHTML=state.challenges.map(c=>{c.checkins=c.checkins||[];const streak=calcStreak(c.checkins);return `<article class="challenge-card ${c.done?'complete':''}"><div class="challenge-icon">✦</div><div class="challenge-main"><div class="row-between"><div><span class="tag">${esc(c.category)}</span><h3>${esc(c.title)}</h3></div><strong>${Math.round(c.progress/c.target*100)}%</strong></div><div class="progress"><span style="width:${Math.min(100,c.progress/c.target*100)}%"></span></div><div class="row-between"><small>${c.progress}/${c.target} keer · ${c.points} punten · 🔥 ${streak} dagen</small><button class="button button-secondary button-small challenge-progress" data-id="${c.id}">${c.checkins.includes(todayKey())?'Vandaag gedaan ✓':'＋ Check-in'}</button></div><div class="streak-days">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const k=d.toISOString().slice(0,10);return `<label class="streak-day"><input type="checkbox" class="streak-check" data-id="${c.id}" data-date="${k}" ${c.checkins.includes(k)?'checked':''}><small>${d.toLocaleDateString('nl-NL',{weekday:'short'}).slice(0,2)}</small></label>`}).join('')}</div></div></article>`}).join('')}
function calcStreak(days=[]){let n=0,d=new Date();if(!days.includes(todayKey()))d.setDate(d.getDate()-1);while(days.includes(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function renderPrograms(){const el=$('#program-list');if(!el)return;el.innerHTML=state.programs.map(p=>`<article class="challenge-card"><div class="challenge-icon">📆</div><div class="challenge-main"><span class="tag">${esc(p.category)}</span><h3>${esc(p.title)}</h3><div class="progress"><span style="width:${p.steps.length?p.steps.filter(s=>s.done).length/p.steps.length*100:0}%"></span></div><small>${p.steps.filter(s=>s.done).length}/${p.steps.length} stappen · ${calcStreak(p.checkins||[])} dagen streak</small><div class="program-steps">${p.steps.map((st,i)=>`<label class="setting-row"><span>${i+1}. ${esc(st.text)}</span><input type="checkbox" class="program-step-check" data-id="${p.id}" data-index="${i}" ${st.done?'checked':''}></label>`).join('')}</div><button class="button button-secondary button-small delete-generic" data-type="programs" data-id="${p.id}">Programma verwijderen</button></div></article>`).join('')||'<div class="empty-row">Nog geen programma’s. Maak er een hierboven of importeer JSON.</div>'}
function renderDeals(){const el=$('#deal-list');if(!el)return;const today=todayKey();el.innerHTML=state.deals.filter(d=>!d.valid||d.valid>=today).map(d=>{const match=state.groceries.some(g=>!g.done&&g.name.toLowerCase().includes(d.product.toLowerCase())||!g.done&&d.product.toLowerCase().includes(g.name.toLowerCase()));return `<article class="list-card ${match?'warning':''}"><div><strong>${esc(d.product)} · € ${Number(d.price).toFixed(2)}</strong><small>${esc(d.store)} · geldig t/m ${esc(d.valid||'onbekend')} ${match?'· Match met boodschappenlijst!':''}</small></div><div class="button-row"><button class="button button-secondary button-small deal-add" data-id="${d.id}">＋ Boodschappen</button><button class="icon-button delete-generic" data-type="deals" data-id="${d.id}">×</button></div></article>`}).join('')||'<div class="empty-row">Geen actuele aanbiedingen. Voeg een aanbieding toe; automatische winkeldata is niet aangesloten.</div>'}
async function renderWeather(){const el=$('#weather-current');if(!el)return;if(!weatherLoaded){el.innerHTML='<div class="empty-row">Haal weergegevens op om de verwachting te bekijken.</div>';return}el.innerHTML=weatherLoaded.current.map(x=>`<article class="challenge-card"><div class="challenge-icon">${x.icon}</div><div class="challenge-main"><small>${esc(x.label)}</small><h3>${esc(x.value)}</h3></div></article>`).join('');$('#weather-hourly').innerHTML=weatherLoaded.hourly.map(x=>`<li class="list-card"><div><strong>${esc(x.time)}</strong><small>${x.temp}°C · regen ${x.rain}% (${x.precip} mm) · wind ${x.wind} km/u · zicht ${x.visibility} km</small></div></li>`).join('');$('#weather-daily').innerHTML=weatherLoaded.daily.map(x=>`<li class="list-card"><div><strong>${esc(x.date)}</strong><small>${x.min}–${x.max}°C · regen ${x.rain}% (${x.precip} mm) · UV ${x.uv} · zonsopkomst ${x.sunrise} · zonsondergang ${x.sunset}</small></div></li>`).join('');}
let weatherLoaded=null;
async function loadWeather(){const status=$('#weather-status');status.textContent='Weergegevens ophalen…';try{let lat=Number($('#weather-lat').value),lon=Number($('#weather-lon').value);const place=$('#weather-place').value.trim();if(place){const gr=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(place)}&count=1&language=nl&format=json`);const gj=await gr.json();if(!gj.results?.length)throw Error('Plaats niet gevonden');lat=gj.results[0].latitude;lon=gj.results[0].longitude;$('#weather-lat').value=lat;$('#weather-lon').value=lon;}else if(navigator.geolocation){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:3500}));lat=pos.coords.latitude;lon=pos.coords.longitude;$('#weather-lat').value=lat;$('#weather-lon').value=lon}catch{}}const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,wind_speed_10m,wind_gusts_10m,uv_index,is_day&hourly=temperature_2m,precipitation_probability,precipitation,wind_speed_10m,visibility&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,uv_index_max,sunrise,sunset&timezone=auto&forecast_days=7`;const r=await fetch(u);if(!r.ok)throw Error('Weerbron niet bereikbaar');const d=await r.json(),c=d.current;weatherLoaded={current:[{icon:'🌡️',label:'Temperatuur / gevoel',value:`${c.temperature_2m}°C / ${c.apparent_temperature}°C`},{icon:'💧',label:'Luchtvochtigheid',value:`${c.relative_humidity_2m}%`},{icon:'🌧️',label:'Neerslag nu',value:`${c.precipitation} mm`},{icon:'💨',label:'Wind / windstoten',value:`${c.wind_speed_10m} / ${c.wind_gusts_10m} km/u`},{icon:'☀️',label:'UV-index',value:String(c.uv_index)}],hourly:d.hourly.time.slice(0,24).map((t,i)=>({time:t.slice(11,16),temp:d.hourly.temperature_2m[i],rain:d.hourly.precipitation_probability[i],wind:d.hourly.wind_speed_10m[i],gust:undefined,visibility:d.hourly.visibility[i]/1000,precip:d.hourly.precipitation[i]})),daily:d.daily.time.map((t,i)=>({date:t,min:d.daily.temperature_2m_min[i],max:d.daily.temperature_2m_max[i],rain:d.daily.precipitation_probability_max[i],precip:d.daily.precipitation_sum[i],uv:d.daily.uv_index_max[i],sunrise:d.daily.sunrise[i].slice(11,16),sunset:d.daily.sunset[i].slice(11,16)}))};status.textContent=`Actuele gegevens geladen van Open-Meteo · ${lat.toFixed(3)}, ${lon.toFixed(3)}. Toont actuele waarden en voorspellingen rechtstreeks van de weerbron.`;renderWeather()}catch(e){status.textContent='Weer kon niet worden geladen. Controleer internetverbinding en coördinaten. Er worden geen voorspellingen verzonnen.';weatherLoaded=null;renderWeather()}}

function renderMeals(){const el=$('#meal-list');el.innerHTML=state.meals.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<li class="list-card"><div><strong>${esc(x.name)}</strong><small>${esc(x.date)} · ${esc(x.person||'Samen')}</small></div><button class="icon-button delete-generic" data-type="meals" data-id="${x.id}">×</button></li>`).join('')||'<li class="empty-row">Plan je eerste maaltijd.</li>'}
function renderGroceries(){const el=$('#grocery-list');el.innerHTML=state.groceries.map(x=>`<li class="task-row ${x.done?'is-done':''}" data-id="${x.id}"><input class="grocery-check" type="checkbox" ${x.done?'checked':''}><span class="task-label"><strong>${esc(x.name)}</strong><small>${esc(x.category)} · ${esc(x.person||'Samen')}</small></span><button class="icon-button delete-generic" data-type="groceries" data-id="${x.id}">×</button></li>`).join('')||'<li class="empty-row">Boodschappenlijst is leeg.</li>'}
function renderStock(){const el=$('#stock-list');el.innerHTML=state.stock.map(x=>`<li class="list-card ${Number(x.amount)<=Number(x.min||0)?'warning':''}"><div><strong>${esc(x.name)}</strong><small>${esc(x.amount)} ${esc(x.unit||'stuks')} · minimum ${esc(x.min||0)}</small></div><button class="icon-button delete-generic" data-type="stock" data-id="${x.id}">×</button></li>`).join('')||'<li class="empty-row">Nog geen voorraad.</li>'}
function renderHome(){const el=$('#home-list');el.innerHTML=state.home.map(x=>`<li class="list-card"><div><strong>${esc(x.title)}</strong><small>${esc(x.type)} · ${esc(x.person||'Samen')} · ${esc(x.frequency||'eenmalig')}</small></div><button class="icon-button delete-generic" data-type="home" data-id="${x.id}">×</button></li>`).join('')||'<li class="empty-row">Nog geen woningtaken.</li>'}
function renderBudget(){const b=state.budget;$('#budget-spent').textContent=`€ ${Number(b.spent||0).toFixed(2)}`;$('#budget-limit').textContent=`€ ${Number(b.monthly||0).toFixed(2)}`;$('#budget-bar').style.width=b.monthly?`${Math.min(100,b.spent/b.monthly*100)}%`:'0%';$('#budget-list').innerHTML=(b.items||[]).map(x=>`<li class="list-card"><div><strong>${esc(x.name)}</strong><small>€ ${Number(x.amount).toFixed(2)} · ${esc(x.category)}</small></div><button class="icon-button delete-generic" data-type="budget" data-id="${x.id}">×</button></li>`).join('')||'<li class="empty-row">Nog geen uitgaven.</li>'}
function renderDates(){renderSimpleList('#dates-list',state.dates,'dates','Ideeën toevoegen voor jullie volgende moment samen.')}function renderTravel(){renderSimpleList('#travel-list',state.travel,'travel','Reizen, boekingen en checklists op één plek.')}function renderExtras(){renderSimpleList('#extras-list',state.extras,'extras','Notities, links en ideeën voor later.')}
function renderSimpleList(selector,items,type,empty){const el=$(selector);el.innerHTML=items.map(x=>`<li class="list-card"><div><strong>${esc(x.title)}</strong><small>${esc(x.note||x.date||'')}</small></div><button class="icon-button delete-generic" data-type="${type}" data-id="${x.id}">×</button></li>`).join('')||`<li class="empty-row">${empty}</li>`}
function renderSettings(){const backup=JSON.stringify(state,null,2);$('#settings-summary').textContent=`${state.tasks.length} taken · ${state.groceries.length} boodschappen · ${state.meals.length} maaltijden · ${state.history.length} historie-items`;$('#theme-select').value=state.theme;$('#appearance-select').value=state.appearance||'normal';$('#minimal-color').value=state.minimalColor||'#315f86';$('#minimal-color-row').hidden=(state.appearance||'normal')!=='minimal';$('#notification-toggle').checked=state.notifications;$('#backup-output').value=backup}
function addGeneric(type,obj){state[type].push({id:uid(),...obj});renderPage(state.currentPage);saveState()}
function removeGeneric(type,id){const key=type==='budget'?'items':type; if(type==='budget'){state.budget.items=state.budget.items.filter(x=>x.id!==id);state.budget.spent=state.budget.items.reduce((a,x)=>a+Number(x.amount),0)}else if(state[key])state[key]=state[key].filter(x=>x.id!==id);renderPage(state.currentPage);saveState('Verwijderd')}
function applyTheme(){const root=document.documentElement;const appearance=state.appearance||'normal';const color=state.minimalColor||'#315f86';root.dataset.theme=state.theme;root.dataset.appearance=appearance;if(appearance==='minimal'){root.style.setProperty('--blue',color);root.style.setProperty('--blue-soft',`color-mix(in srgb, ${color} 12%, var(--paper))`)}else{root.style.removeProperty('--blue');root.style.removeProperty('--blue-soft')}}
function closeMenu(){$('.sidebar')?.classList.remove('is-open');$('#mobile-scrim')?.classList.remove('is-visible');$('#menu-toggle')?.setAttribute('aria-expanded','false')}
function bindForms(){
  $('#focus-form').onsubmit=e=>{e.preventDefault();state.focus=$('#focus-input').value.trim();$('#focus-input').value='';renderToday();saveState('Focus opgeslagen')};
  $('#daily-answer-form').onsubmit=e=>{e.preventDefault();state.dailyAnswers=state.dailyAnswers||{};state.dailyAnswers[todayKey()]=$('#daily-answer').value.trim();renderToday();saveState('Antwoord van de dag bewaard')};
  $('#task-form').onsubmit=e=>{e.preventDefault();addTask($('#task-input').value,$('#task-person').value,$('#task-category').value,$('#task-due').value||todayKey());$('#task-input').value=''};
  $('#agenda-form').onsubmit=e=>{e.preventDefault();addGeneric('agenda',{title:$('#agenda-title').value,date:$('#agenda-date').value,person:$('#agenda-person').value});e.target.reset()};
  $('#challenge-form').onsubmit=e=>{e.preventDefault();addGeneric('challenges',{title:$('#challenge-title').value,category:$('#challenge-category').value,target:Number($('#challenge-target').value),progress:0,points:Number($('#challenge-points').value),done:false,checkins:[]});e.target.reset()};
  $('#deal-form').onsubmit=e=>{e.preventDefault();addGeneric('deals',{product:$('#deal-product').value.trim(),store:$('#deal-store').value.trim(),price:Number($('#deal-price').value),valid:$('#deal-valid').value,saved:true});e.target.reset()};
  $('#program-form').onsubmit=e=>{e.preventDefault();addGeneric('programs',{title:$('#program-title').value.trim(),category:$('#program-category').value.trim(),steps:$('#program-steps').value.split(';').map(x=>x.trim()).filter(Boolean).map(text=>({text,done:false})),checkins:[]});e.target.reset()};
  $('#meal-form').onsubmit=e=>{e.preventDefault();addGeneric('meals',{name:$('#meal-name').value,date:$('#meal-date').value,person:$('#meal-person').value});e.target.reset()};
  $('#grocery-form').onsubmit=e=>{e.preventDefault();addGeneric('groceries',{name:$('#grocery-name').value,category:$('#grocery-category').value,person:$('#grocery-person').value,done:false});e.target.reset()};
  $('#stock-form').onsubmit=e=>{e.preventDefault();addGeneric('stock',{name:$('#stock-name').value,amount:$('#stock-amount').value,unit:$('#stock-unit').value,min:$('#stock-min').value});e.target.reset()};
  $('#home-form').onsubmit=e=>{e.preventDefault();addGeneric('home',{title:$('#home-title').value,type:$('#home-type').value,person:$('#home-person').value,frequency:$('#home-frequency').value});e.target.reset()};
  $('#budget-form').onsubmit=e=>{e.preventDefault();const amount=Number($('#budget-amount').value)||0;state.budget.monthly=Number($('#budget-monthly').value)||state.budget.monthly;state.budget.items.unshift({id:uid(),name:$('#budget-name').value,amount,category:$('#budget-category').value});state.budget.spent=state.budget.items.reduce((a,x)=>a+Number(x.amount),0);renderBudget();saveState();e.target.reset()};
  $('#simple-form').onsubmit=e=>{e.preventDefault();const page=state.currentPage;const map={dates:'dates',travel:'travel',extras:'extras'};const key=map[page];if(!key)return;addGeneric(key,{title:$('#simple-title').value,note:$('#simple-note').value,date:$('#simple-date').value});e.target.reset()};
}
function handleClicks(e){if(e.target.closest('#program-import-open')){$('#program-import').click();return}const deal=e.target.closest('.deal-add');if(deal){const d=state.deals.find(x=>x.id===deal.dataset.id);if(d){state.groceries.unshift({id:uid(),name:d.product,category:'Aanbieding',person:'Samen',done:false,dealStore:d.store,dealPrice:d.price});saveState('Product toegevoegd aan boodschappenlijst');renderDeals()}return}const nav=e.target.closest('[data-page-link]');if(nav){e.preventDefault();showPage(nav.dataset.pageLink);return}const del=e.target.closest('.task-delete');if(del){deleteTask(del.closest('[data-id]').dataset.id);return}const generic=e.target.closest('.delete-generic');if(generic){removeGeneric(generic.dataset.type,generic.dataset.id);return}const challenge=e.target.closest('.challenge-progress');if(challenge){const c=state.challenges.find(x=>x.id===challenge.dataset.id);if(c){c.progress=Math.min(c.target,c.progress+1);c.done=c.progress>=c.target;renderChallenges();renderToday();saveState(c.done?'Challenge voltooid 🎉':'Voortgang opgeslagen')}return}if(e.target.matches('.streak-check')){const c=state.challenges.find(x=>x.id===e.target.dataset.id);if(c){c.checkins=c.checkins||[];const date=e.target.dataset.date,was=c.checkins.includes(date);c.checkins=e.target.checked?[...new Set([...c.checkins,date])]:c.checkins.filter(d=>d!==date);if(date===todayKey()&&e.target.checked&&!was){c.progress=Math.min(c.target,(c.progress||0)+1);c.done=c.progress>=c.target}else if(date===todayKey()&&!e.target.checked&&was){c.progress=Math.max(0,(c.progress||0)-1);c.done=c.progress>=c.target}renderChallenges();renderToday();saveState('Streak en punten bijgewerkt')}return}if(e.target.matches('.program-step-check')){const p=state.programs.find(x=>x.id===e.target.dataset.id);if(p){p.steps[Number(e.target.dataset.index)].done=e.target.checked;if(e.target.checked){p.checkins=p.checkins||[];if(!p.checkins.includes(todayKey()))p.checkins.push(todayKey())}renderPrograms();saveState('Programmastap bijgewerkt')}return}if(e.target.matches('.grocery-check')){const item=state.groceries.find(x=>x.id===e.target.closest('[data-id]').dataset.id);if(item){item.done=e.target.checked;renderGroceries();saveState()}}}
function handleChanges(e){if(e.target.matches('.task-check'))toggleTask(e.target.closest('[data-id]').dataset.id);if(e.target.id==='theme-select'){state.theme=e.target.value;applyTheme();saveState('Thema aangepast')}if(e.target.id==='appearance-select'){state.appearance=e.target.value;applyTheme();renderSettings();saveState('Vormgeving aangepast')}if(e.target.id==='minimal-color'){state.minimalColor=e.target.value;applyTheme();saveState('Accentkleur aangepast')}if(e.target.id==='notification-toggle'){state.notifications=e.target.checked;saveState('Instelling opgeslagen')}}
function setupDnD(){let dragged=null;document.addEventListener('dragstart',e=>{const row=e.target.closest('.task-row[draggable]');if(row)dragged=row});document.addEventListener('dragover',e=>{if(e.target.closest('.task-row[draggable]'))e.preventDefault()});document.addEventListener('drop',e=>{const target=e.target.closest('.task-row[draggable]');if(!dragged||!target||dragged===target)return;e.preventDefault();const a=state.tasks.findIndex(x=>x.id===dragged.dataset.id),b=state.tasks.findIndex(x=>x.id===target.dataset.id);const [item]=state.tasks.splice(a,1);state.tasks.splice(b,0,item);renderTasksPage();renderToday();saveState('Volgorde opgeslagen');dragged=null})}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`samen-thuis-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{state=merge(defaultState(),JSON.parse(reader.result));applyTheme();renderPage(state.currentPage);saveState('Back-up geïmporteerd')}catch{toast('Ongeldig back-upbestand')}};reader.readAsText(file)}
function init(){applyTheme();bindForms();document.addEventListener('click',handleClicks);document.addEventListener('change',handleChanges);$$('[data-page-link]').forEach(()=>{});$('#menu-toggle').onclick=()=>{const open=$('.sidebar').classList.toggle('is-open');$('#mobile-scrim').classList.toggle('is-visible',open);$('#menu-toggle').setAttribute('aria-expanded',open)};$('#mobile-scrim').onclick=closeMenu;$('#quick-add-open').onclick=()=>$('#quick-add-dialog').showModal();$('#quick-add-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});$$('.quick-add-options button').forEach(b=>b.onclick=()=>{const action=b.dataset.quickAction;$('#quick-add-dialog').close();showPage(action==='task'?'tasks':action==='focus'?'today':'extras');setTimeout(()=>$(action==='task'?'#task-input':action==='focus'?'#focus-input':'#simple-title')?.focus(),50)});$('#weather-form').onsubmit=e=>{e.preventDefault();loadWeather()};$('#weather-refresh').onclick=loadWeather;$('#program-import').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const j=JSON.parse(rd.result);const items=Array.isArray(j)?j:(j.programs||[j]);items.forEach(x=>{if(!x.title||!Array.isArray(x.steps))throw Error();addGeneric('programs',{title:String(x.title),category:String(x.category||'Eigen'),steps:x.steps.map(s=>typeof s==='string'?{text:s,done:false}:{text:String(s.text||s.title||''),done:!!s.done}).filter(s=>s.text),checkins:[]})});toast('Programma-import voltooid')}catch{toast('Import mislukt. Verwacht JSON met title, category en steps.')}e.target.value=''};rd.readAsText(f)};$('#export-data').onclick=exportData;$('#import-file').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#clear-data').onclick=()=>{if(confirm('Alle lokale testdata wissen?')){state=defaultState();applyTheme();renderPage('today');saveState('Testdata gewist')}};$('#page-content').addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});showPage(state.currentPage);renderDeals();renderPrograms();if(state.currentPage==='weather')loadWeather()}
document.addEventListener('DOMContentLoaded',init);
